import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Roboto, 
} from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import Navbar from "@/components/navbar";
import SessionUpdater from "@/components/SessionUpdater";
import { validateStartupEnv } from "@/lib/env";

validateStartupEnv();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Navbar />
          <SessionUpdater />{" "}
          {/* Add SessionUpdater here to keep Redux in sync with NextAuth session */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
